name: Terraform Destroy

on:
  workflow_dispatch:  # manually triggered

jobs:
  terraform-destroy-plan:
    name: Terraform Destroy Plan
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="bucket=kf-test-tf-state-bucket" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=ap-south-1"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Terraform Destroy Plan
        working-directory: ./terraform
        run: terraform plan -destroy -out=tfplan-destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Upload Destroy Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-destroy-plan-artifact
          path: ./terraform/tfplan-destroy

  terraform-destroy-apply:
    name: Terraform Destroy Apply
    runs-on: ubuntu-22.04
    needs: terraform-destroy-plan
    environment:
      name: production   # manual approval before running

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Destroy Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-destroy-plan-artifact
          path: ./terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="bucket=kf-test-tf-state-bucket" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=ap-south-1"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Terraform Apply Destroy Plan
        working-directory: ./terraform
        run: terraform apply tfplan-destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
